server:
  port: 3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia_db?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: academia
    password: queiroz
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate_format_sql: true


logging:
  level:
    org:
      hibernate:
        type: trace
