app:
  message: This is the property file to the ${spring.application.name} specific to Prod environment

#spring.datasource.driver-class-name=com.mysql
#spring.datasource.url=<MYSQL_URL>
#spring.datasource.username=<USERNAME>
#spring.datasource.password=<PASSWORD>

spring:
  datasource:
    driver-class-name:com.mysql
    url:<MYSQL_URL>
    username:<USERNAME>
    password:<PASSWORD>